# -*- coding: utf-8 -*-
"""shikaku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wz67jAS7dPefMESLCxeicU-UwFiB73qQ
"""

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import japanize_matplotlib  # 日本語ラベルのためのライブラリ
import os

# --- 設定項目 ---
# 1. Google Drive上のCSVファイルのパスをここに設定
# Google Colabで左側のファイルエクスプローラーからCSVを右クリックし、「パスをコピー」で取得できます。
file_path = '/content/drive/MyDrive/data/sample_data.csv'

# 2. グラフを保存する場所とファイル名
output_dir = 'output'
output_filename = 'correlation_network.png'

# 3. グラフに表示する相関の閾値（これより強い相関のみ線で結ぶ）
correlation_threshold = 0.5
# --- 設定はここまで ---

def create_correlation_network(df, threshold):
    """データフレームから相関ネットワークグラフを生成する関数"""

    # 数値型のカラムのみを選択（カテゴリ変数などを除外）
    numeric_df = df.select_dtypes(include=np.number)
    print(f"分析対象のカラム: {numeric_df.columns.tolist()}")

    # 相関行列を計算
    corr_matrix = numeric_df.corr()

    # ネットワークグラフのオブジェクトを作成
    G = nx.Graph()

    # 閾値以上の相関を持つペアをエッジとして追加
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            corr_value = corr_matrix.iloc[i, j]
            if abs(corr_value) > threshold:
                G.add_edge(corr_matrix.columns[i], corr_matrix.columns[j],
                           weight=abs(corr_value),
                           sign=np.sign(corr_value))
    return G

def draw_and_save_graph(G, output_path):
    """ネットワークグラフを描画してファイルに保存する関数"""

    if not G.nodes():
        print("閾値を超える相関が見つからなかったため、グラフは生成されませんでした。")
        return

    plt.figure(figsize=(14, 14))

    # ノードの配置を計算
    pos = nx.spring_layout(G, k=0.8, seed=42)

    # 線の太さと色をリストで準備
    weights = [G[u][v]['weight'] * 5 for u, v in G.edges()]
    edge_colors = ['red' if G[u][v]['sign'] > 0 else 'blue' for u, v in G.edges()]

    # 描画
    nx.draw_networkx(G, pos,
                     with_labels=True,
                     node_color='skyblue',
                     node_size=2500,
                     font_size=12,
                     font_family='IPAexGothic',
                     width=weights,
                     edge_color=edge_colors)

    plt.title('相関ネットワークグラフ (赤: 正の相関, 青: 負の相関)', fontsize=18)

    # フォルダがなければ作成
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # ファイルに保存
    plt.savefig(output_path, bbox_inches='tight')
    print(f"グラフを {output_path} に保存しました。")
    plt.close()


if __name__ == '__main__':
    try:
        # CSVファイルを読み込む
        df = pd.read_csv(file_path)
        print(f"{file_path} の読み込みに成功しました。")

        # グラフを生成
        graph = create_correlation_network(df, correlation_threshold)

        # グラフを描画して保存
        output_path = os.path.join(output_dir, output_filename)
        draw_and_save_graph(graph, output_path)

    except FileNotFoundError:
        print(f"エラー: ファイルが見つかりません。パスを確認してください: {file_path}")
    except Exception as e:
        print(f"エラーが発生しました: {e}")